name: poc_geo
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  hive: ^2.2.3
  hive_flutter: ^1.1.0
  geolocator: ^9.0.2
  flutter_map: ^4.0.0
  latlong2: ^0.8.1   
  dartz: ^0.10.1
  dio: ^4.0.6
  flutter_modular: ^5.0.3
  mocktail: ^0.3.0
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  hive_generator: ^2.0.0
  build_runner: ^2.4.0

flutter:
  uses-material-design: true

  assets:
    - assets/global_plants.json
